### ISSUE TITLE
Testing problems found in Laval with Gen 2 Setup

### ISSUE THREAD

**Issue by MorrisAV** [TestUpCommunity/TUGithubAPI#740]
Wells,

Here is a set of problems found when testing
[List - Defect Log 20190614.xlsx](https://github.com/TestUpCommunity/TUGithubAPI/files/3292062/List.-.Defect.Log.20190614.xlsx)

**Comment by zhangting85** [comment]
sorry but this repo is still not released, and if you found error, don't use attachment which may contain virus
